### ISSUE TITLE
[BUG] Up does nothing after you open info until you press down or close info

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#59] opened 2020-08-12 07:43 UTC
Once you open the info of a process the selection bar disappears. In this state pressing down brings back the selection bar on the row below where it was when you opened the process info. Pressing up in this state doesn't do anything. Once the selection bar is on screen again you can navigate normally.

This is probably a holdover from before it started remembering your position in the proc list.

**Comment by aristocratos** [comment] 2020-08-12 14:39
Not a bug but intentional. When pressing enter your selection is equal to zero. Pressing down or closing the info box moves you back down to last selection. But pressing up to get back down to the process list doesn't make much sense in my mind since the currently focused object is the info box.

**Comment by drazil100** [comment] 2020-08-12 18:03
It's a little weird I have to push down to push up is why I thought it was a bug.

**Closed** 2020-08-14 16:16 UTC
Labels: bug
