### ISSUE TITLE
[BUG] diamonds instead of dots in console mode

### ISSUE THREAD

**Issue by dszubov** [aristocratos/bpytop#390] opened 2022-09-25 08:20 UTC
**Describe the bug**

in debian server (promxox pve in fact), the bpytop is displayed incorrectly in console mode - diamonds instead of dots

**To Reproduce**

start the server, wait for the final boot, log in via console mode (monitor with keyboard attached to server), run bpytop

**Expected behavior**

at startup, bpytop is displayed correctly (small dots instead of diamonds)

**Screenshots**

![IMG_0036](https://user-images.githubusercontent.com/104792259/192134545-3d72e3a1-d9f5-45a8-83f1-1177f152260b.jpg)

**Info (please complete the following information):**
 - bpytop version: 1.0.61
 - psutil version: 5.8.0
 - (Linux) Linux distribution and version: proxmox 7.2 (based on debain 11), pve 5.15.30-3
 - Terminal used: system's console default 
 - Font used: system's default
 - Python version: 3.9.2

**Additional context**

I do not attach the error log because, with the exception of the bpytop display, it works correctly

**Comment by zampierilucas** [comment] 2022-09-26 11:41
This is not a bug with Byton, but due to the fact that you're using bare terminal instead of a virtual terminal, look it up kernel VT.

Either way, personally I run a proxmox installation myself, with kmscon on startup to run bpytop 'correctly'.

Closing this.

**Closed by zampierilucas** 2022-09-26 11:41 UTC
Labels: bug
