### ISSUE TITLE
[REQUEST] add hostname to title bar

### ISSUE THREAD

**Issue by joeroback** [aristocratos/bpytop#133] opened 2020-09-22 15:08 UTC
bpytop is awesome, so awesome, that i use it to monitor multiple machines, and not having the hostname in the title it can be confusing as to which instance is which!

**Comment by aristocratos** [comment] 2020-09-22 15:35
@joeroback 
BpyTOP will prepend anything contained in the environment variable `TERMINAL_TITLE` to the title it sets.

So you could for example add  `declare -x TERMINAL_TITLE="$(hostname)"` to your `.bashrc` (or the config for any other shell you are using) and the title in BpyTOP would show up as `yourhostname BpyTOP`.

Wouldn't want to hardcode the hostname to the title since it's not uncommon for terminals to have the option for formatting the title in which most likely hostname would be included.

**Comment by joeroback** [comment] 2020-09-23 02:21
i was thinking more in the space near the time, since i sometimes have terminals frameless, like widgets on the desktop... so i have no OS frame or title bar.. but `TERMINAL_TITLE` is at least something! thanks

**Comment by RedBearAK** [comment] 2020-09-23 07:40
@joeroback 

>i was thinking more in the space near the time, since i sometimes have terminals frameless, like widgets on the desktop

Another makeshift solution if you don't have window titlebars available is to set a custom CPU name in the options. That will at least let you tell the BpyTOP instances apart. There should be room for 19 characters if temp display is enabled.

**Comment by RedBearAK** [comment] 2020-09-23 07:55
@aristocratos 

I think a lot of the users who are likely to use BpyTOP frequently may be using frameless window managers like @joeroback does, and want to monitor multiple machines. 

Suggestion: Allow optional hostname / IP address to display on the bottom line of the network box. There's plenty of room at the smallest window size, and the process box already sets the precedent of having text elements on the bottom line.

**Comment by aristocratos** [comment] 2020-09-25 12:06
@joeroback @RedBearAK 
A solution to this could be to add some custom formatting options to the clock format. This could include other system information that people would find desirable, as long as they are available through the already used libraries.

For example:
`/host` in the clock format could be used to get `os.uname()[1]` which should return the hostname.

**Comment by joeroback** [comment] 2020-09-25 13:44
> @joeroback @RedBearAK
> A solution to this could be to add some custom formatting options to the clock format. This could include other system information that people would find desirable, as long as they are available through the already used libraries.
> 
> For example:
> `/host` in the clock format could be used to get `os.uname()[1]` which should return the hostname.

yea, that sounds neat. could expand to other common formatting things in the future as well!

**Comment by aristocratos** [comment] 2020-09-26 21:54
@joeroback 
Added `/host` and `/user` as clock formatting options, set in the options menu and it should work.

**Comment by RedBearAK** [comment] 2020-09-27 00:40
@aristocratos 

It works, but some feedback. 

Due to the large number of horizontal line symbols on either side of the clock element, both the battery element and the mode element get partially clobbered at the 80x24 window size. There is insufficient room for even the full hostname to be displayed at that window size, much less the user name. And this machine has one of the shortest hostnames on my network. 

I have another machine named "sager-mint", without even a domain extension. That already starts to clobber the mode element at 80x24. 

This solution feels less than optimal for any window width less than about 96 characters, or wider if the hostname is even longer. Usable under many circumstances of course, but not refined on par with the rest of the UI choices. 

![Screen Shot 2020-09-26 at 3 35 43 PM](https://user-images.githubusercontent.com/64876997/94352166-2c6fd200-000e-11eb-8c5f-f4f9633b4866.png)

I don't think I'm alone in tending to create hostnames that let me break up a network into different sections visually in the network browser, or to help me distinguish between local machines and machines on a remote network. That means the first part of the hostname will often be the same as other machines on the network, with the unique part at the very end of the hostname. Like this: 

NETW2-MacBookPro29.local
NETW2-MacBookPro23.local

This means that if you don't have room to display the entire hostname, it could be impossible to tell the machines apart. 

My 17-inch MBP has a 1920x1200 display. If I want to show two bpytop instances side by side at a reasonable font size, I have room for about 96 characters in each window. That's pretty limiting. And many laptops still have lower than 1080p resolutions. 

Sure, you can use wide horizontal windows, but what if you want to monitor three or four machines at the same time? That will usually result in quartering the screen when possible. Even on a 1080p display this means the windows have to be fairly small. 

If it's possible to take out some of the horizontal line symbols around the clock, that will help free up more room for showing hostname characters at smaller window sizes. 

Besides using the bottom line of the CPU box to display this kind of information, I don't know what else you could have done.

**Comment by aristocratos** [comment] 2020-09-27 08:19
@RedBearAK 
> If it's possible to take out some of the horizontal line symbols around the clock, that will help free up more room for showing hostname characters at smaller window sizes.

I can reduce the amount of horizontal lines a bit, but the problem is that the clock function doesn't know how much space it has available, it's not drawn in the same thread as the other elements. And the used space by the clock can change between updates depending on what formatting is used, so it needs to have some horizontal lines to compensate.
I can change so it saves the length of the old value and compares with the new to dynamically change the amount of horizontal lines that get redrawn.

One thing I would argue though is that if you've got multiple instances of bpytop from different machines running, maybe you don't need the clock showing in all of them, but just the hostname to differentiate between them.

**Comment by aristocratos** [comment] 2020-09-27 20:12
Fixed in v1.0.39
The battery stats will however draw over the clock if it's too long on small terminal sizes.

**Comment by RedBearAK** [comment] 2020-09-27 21:55
@aristocratos 

Haven't seen any problem on Linux but I'm now getting a showstopper crash when starting bpytop on Mac. 

```
27/09/20 (13:40:56) | ERROR: Data collection thread failed with exception: [Errno 2] No such file or directory: '/sys/class/power_supply'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 2581, in _runner
    collector._draw()
  File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 2817, in _draw
    CpuBox._draw_fg()
  File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 1704, in _draw_fg
    if CONFIG.show_battery and cls.battery_activity():
  File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 1640, in battery_activity
    for directory in os.listdir("/sys/class/power_supply"):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply'

27/09/20 (13:43:27) | ERROR: Data collection thread failed with exception: [Errno 2] No such file or directory: '/sys/class/power_supply'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 2581, in _runner
    collector._draw()
  File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 2817, in _draw
    CpuBox._draw_fg()
  File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 1704, in _draw_fg
    if CONFIG.show_battery and cls.battery_activity():
  File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 1640, in battery_activity
    for directory in os.listdir("/sys/class/power_supply"):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply'
27/09/20 (13:43:27) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 
```

After clearing `bpytop.conf` I get stuck at the init screen and can't quit or even Ctrl+C out of it. Running bpytop in a separate terminal window (I'm using iTerm2) results in a crash, with the second error block above. The first error block never finished because that instance of bpytop locked up. 

![Screen Shot 2020-09-27 at 1 42 51 PM](https://user-images.githubusercontent.com/64876997/94376663-6a313100-00c8-11eb-8523-e2c2ae53fa0a.png)

**Comment by RedBearAK** [comment] 2020-09-27 22:09
@aristocratos 

>One thing I would argue though is that if you've got multiple instances of bpytop from different machines running, maybe you don't need the clock showing in all of them, but just the hostname to differentiate between them.

Yeah, I thought about that option, but don't forget that remote machines can easily be in different time zones. Removing the clock will often be less than helpful. In fact many users would probably want to add the time zone code to the clock display to help remind them where the remote machine is physically located. Sometimes that's important.

**Comment by RedBearAK** [comment] 2020-09-27 22:49
@aristocratos 

The horizontal line issue appears to be solved. I have the clock, time zone (%Z takes four characters plus spaces), hostname and user set to display on the P4 laptop. Everything shows but the user name at 80x24, and the mode element no longer gets clobbered. I don't have the battery element on that machine but I assume the problem should be fixed on that side also. 

So that fix seems to be working really well all the way down to 80x24, regardless of the content of the clock element. The limited space is now being used far more effectively. 

Well done.

**Comment by RedBearAK** [comment] 2020-09-27 23:27
@aristocratos 

I don't actually know how much sense this makes but I feel like it might be a good idea to strip ".local" from hostnames that report that way via `uname`. 

My P4 Linux laptop is pingable from my Mac with `ping sager-mint.local` but `uname` on that machine reports as just "sager-mint" so that's all that gets displayed in bpytop, without the ".local". But on the Mac, `uname` reports the hostname as "RBNS-Tech.local", so that is what bpytop displays. 

I feel like most people who care about showing hostnames in bpytop would also know that they would need to add ".local" to ping or connect to a local machine with a working zeroconf setup. So allowing that to be displayed seems like a pointless waste of precious space. 

Therefore, if you can strip ".local" from the end of the reported hostname, I think that would be a good enhancement of this hostname display function. That's six characters of space saved right there, on any system that reports that way.

**Comment by RedBearAK** [comment] 2020-09-28 03:37
@aristocratos 

This is probably obvious, but I was able to bypass the startup crash on macOS by opening the conf file and manually setting `show_battery` to False. Setting it back to True from inside bpytop results in an instant crash to terminal. 

Strange since I haven't had an issue with the battery info in previous versions.

**Comment by aristocratos** [comment] 2020-09-28 19:05
@RedBearAK 

> I don't actually know how much sense this makes but I feel like it might be a good idea to strip ".local" from hostnames that report that way via uname.

I rather not mess with the output from uname since that is the actual hostname, the same hostname is also reported by `/bin/hostname`.

If you don't want the `.local` you can change hostname with `sudo scutil --set HostName newhostname` and `.local` will disappear.

**Comment by RedBearAK** [comment] 2020-09-28 20:26
@aristocratos 

Having used macOS for nearly 20 years I've been very happy with the way it manages its own network setup to make all sorts of network functions between Macs work very well. I would never want to manually mess with the hostname rather than changing it through the established GUI preference pane, where it doesn't show the ".local" or allow it to be edited. Even if for no other reason than I would have to do that manually on every Mac I ever run bpytop on. 

I understand not wanting to edit the reported hostname for other FQDNs. But I was hoping a special exception could be made for ".local" since some systems that are obviously pingable/connectable via ".local", and therefore are using Bonjour/ZeroConf, appear to already treat it as irrelevant for reporting via `uname`. 

Speaking of FQDNs, they can be pretty long, and often irrelevant to the user, for instance if all the machines they are monitoring are on the same FQDN, or the names are unique enough that the FQDN is unnecessary to tell them apart easily. So what about optionally allowing the user to display the FQDN or only the "short" hostname, i.e. the part before the first dot? That would cover the ".local" scenario and many others. I think a lot of users would like that option.

**Comment by RedBearAK** [comment] 2020-09-28 20:28
@aristocratos 

I didn't see a notice about it but the battery info crash on macOS is gone for me in 1.0.40.

**Comment by RedBearAK** [comment] 2020-09-28 22:31
@aristocratos 

Looks like I spoke too soon about the clock sizing being OK on the battery info side. Once the battery element expands from its smallest size to the colorful graph size at the 100-character window width there are some bad things happening. 

To be fair, this is with `%X %Z /host /user`, but it would also happen with any sufficiently long hostname all by itself. 

![battery_clobbering](https://user-images.githubusercontent.com/64876997/94489465-f7d85380-0190-11eb-9a1a-e498d611d7e9.png)

Seems to be room for 34 characters in the clock element at 100-character width before it would bump up against the expanded battery element. 

![clock_100ch_34ch](https://user-images.githubusercontent.com/64876997/94490198-6964d180-0192-11eb-9a73-534646da8897.png)


If the battery element were to be forced to remain at the smaller size when there is too much text to be displayed inside the clock element, there would be room for a total of 44 characters at the 100-character width, limited by the clock element bumping into the mode element on the left side. I suppose that should be blindingly obvious since the battery graph is 10 characters. 

This screenshot is just before the expansion of the battery element, at 99 characters with the clock element showing 43 characters: 

![clock_99ch_43ch](https://user-images.githubusercontent.com/64876997/94491406-a9c54f00-0194-11eb-9240-0fef6242b9fe.png)

If you were some kind of lunatic you could theoretically balance things out by making a different "short" mode for the battery info where you shorten "BAT" to "B" (or just the charging symbol) and insert a four-character colored battery graph... Then again, both the update interval and the battery percentage are able to change in length. 

The Earl of Lemongrab says things that change in length are unacceptable. 

![unacceptable](https://user-images.githubusercontent.com/64876997/94492298-7b487380-0196-11eb-8f4d-298682916fe6.gif)

**Comment by RedBearAK** [comment] 2020-09-28 22:59
@aristocratos 

Haha, I set the clock back to normal after all that testing with excessive text and got a somewhat unexpected result. 

![clock_unexpected](https://user-images.githubusercontent.com/64876997/94492863-b8613580-0197-11eb-84bd-f22b4fa93d81.png)

It actually disappears for a moment after reverting the clock to normal, but then the text reappears and stays there until I quit and restart the app. 

Looks like under some circumstance something isn't resetting the horizontal line characters properly. 

I have had a somewhat difficult time replicating this. I think one of the keys is displaying all the text and then resizing the window at least once, then setting the clock back to normal. That seems to be the only way to get the text to stick like this. 

Resizing the window again fixes it without quitting. 

I can't replicate this when just sticking to the interpretable options like `%X %Z /host /user` and trying to revert to just `%X`. Even with window resizing while the additional text is displayed. Everything works as normal. 

If it is intended that the user can just enter any random text in the clock element, that could be offered as another solution for telling BpyTOP instances apart. Makes it just like the custom CPU name. The user could enter anything at all. I didn't actually realize this was possible until I tried it. I was assuming invalid options would just get rejected, as if it would all be validated by the `date` command or something. Seemed logical at the time.

**Comment by RedBearAK** [comment] 2020-09-29 00:02
@aristocratos 

I don't know if you intended it to be this way, but I noticed that it's not possible to move the cursor back and forth with the arrow keys while editing the clock config (or the custom CPU name). If you make a mistake or want to edit something in the middle, you have to erase back to where the mistake was and start over. Not a big deal but makes it a little irritating to experiment with the config more than a few times. 

I don't know if there is an easy solution for this. Just wondering.

**Comment by aristocratos** [comment] 2020-10-08 15:48
In v1.0.42
> Added: Stripping of .local from /host clock format

**Comment by joeroback** [comment] 2020-10-08 15:56
@aristocratos btw thanks for this! supporting so many platforms, there will almost always be quirks like the `.local` stuff, but overall i feel like the title/clock area is more useful!

**Comment by RedBearAK** [comment] 2020-10-09 07:55
@aristocratos 

>In v1.0.42
>Added: Stripping of .local from /host clock format

Confirmed working on macOS Mojave. 

Thanks! Really appreciate it.

**Comment by aristocratos** [comment] 2020-10-19 18:56
@RedBearAK 
> but I noticed that it's not possible to move the cursor back and forth with the arrow keys while editing the clock config

The inputting is implemented from scratch so there is no editing included, I could possibly implement it but I would suggest you create a new feature request for it or I will most likely forget.

**Comment by RedBearAK** [comment] 2020-10-21 03:25
@aristocratos 

>The inputting is implemented from scratch so there is no editing included, I could possibly implement it but I would suggest you create a new feature request for it or I will most likely forget.

See issue #155. 

You can now forget about it until you get really bored and need something to do.

**Closed** 2020-10-25 22:38 UTC
Labels: enhancement
