### ISSUE TITLE
[BUG] Program stops after the last network interface

### ISSUE THREAD

**Issue by MondherAb** [aristocratos/bpytop#72] opened 2020-08-17 09:09 UTC
**Describe the bug**

The program stopped instantly with this message when I was going through all my network interfaces: _"Bpytop exited with errorcode (1). See /home/###/.config/bpytop/error.log for more information!"_

**To Reproduce**

1. Execute bpytop
2. _In the "net" division_: click on "n>"  next to the interface name and go through all the network interfaces of the computer. The bug will occur after the last one.

**Expected behavior**

I was expecting from the program to return to the first interface.

**Info**
 - bpytop version: 1.0.16
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Ubuntu 20.04.1 LTS 
 - Terminal used: BASH
 - Font used: Monospace Regular
 - Python version: Python 3.8.2

**Additional context**

<pre>
17/08/20 (10:49:57) | ERROR: Data collection thread failed with exception: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2399, in _runner
    collector._draw()
  File "/usr/local/bin/bpytop", line 2937, in _draw
    NetBox._draw_fg()
  File "/usr/local/bin/bpytop", line 1882, in _draw_fg
    out += f'{Mv.to(y if direction == "download" else y + cls.graph_height["download"], x)}{Graphs.net[direction](None if stats["redraw"] else stats["speed"][-1])}'
  File "/usr/local/bin/bpytop", line 1350, in __call__
    self._create([value])
  File "/usr/local/bin/bpytop", line 1331, in _create
    self.out += f'{"" if not self.colors else self.colors[self.last]}{self.graphs[self.current][0]}'
IndexError: list index out of range
17/08/20 (10:49:57) | WARNING: Exiting with errorcode (1). Runtime 0:01:14
</pre>

**Comment by aristocratos** [comment] 2020-08-18 15:03
Can't reproduce the issue, but looks like it could probably be fixed with some additional error checking in the graph creation functions. Gonna take a look when I've got some time.

**Closed** 2020-10-25 22:35 UTC
Labels: bug
