### ISSUE TITLE
Crash on biew process info

### ISSUE THREAD

**Issue by RomanKharin** [aristocratos/bpytop#11] opened 2020-08-04 07:19 UTC
**Crash on biew process info**

Bpytop exited with errorcode (1). 

**To Reproduce**

v1.0.2 from git, busy system, actively walk on processes, press Enter

**Expected behavior**

View process info

**Info:**
bpytop version: 1.0.2
psutil version: 5.7.2
mate-terminal 1.16.3 + Anka/Coder Condensed
Ubuntu 16.04.6 LTS
Python 3.7.6 (built from source)

**Additional context**
```
04/08/20 (10:11:35) | ERROR: Data collection thread failed with exception: 'cmd'
Traceback (most recent call last):
  File "bpytop.py", line 2319, in _runner
    collector._collect()
  File "bpytop.py", line 2934, in _collect
    cls.details["cmdline"] = cls.processes[c_pid]["cmd"]
KeyError: 'cmd'
04/08/20 (10:11:37) | WARNING: Exiting with errorcode (1). Runtime 0:10:38
```

**Comment by aristocratos** [comment] 2020-08-04 15:01
Duplicate of #11

Will be fixed in v1.0.3 later today.

**Closed by aristocratos** 2020-08-04 15:01 UTC
Labels: bug
