### ISSUE TITLE
[BUG] RuntimeWarning related to psutil at top of screen

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#61] opened 2020-08-13 03:28 UTC
![Screenshot from 2020-08-12 22-19-46](https://user-images.githubusercontent.com/17794391/90090999-0e167700-dceb-11ea-95b7-cf83a6eae40f.png)

bpytop version: 1.0.12

[error.log](https://github.com/aristocratos/bpytop/files/5066988/error.log)

I don't know how to reproduce it unfortunately.

**Comment by aristocratos** [comment] 2020-08-13 18:29
> 12/08/20 (22:21:10) | ERROR: Non fatal error during disk io collection!
> 12/08/20 (22:21:10) | ERROR: Caused by outdated psutil version.

You'll need to update psutil. Will make the read and write speeds for disks show up.

Not sure why that "RuntimeWarning" shows up there though, errors should only be logged to file. Could be leaking through with what should have been the disk io stats after I changed the expection caused by the outdated psutil to a non fatal exception.

**Comment by aristocratos** [comment] 2020-08-13 18:31
If you got psutil installed through your package manager and it's outdated, check if anything depends on it and uninstall if not and install through pip3 instead to always get latest version.

**Comment by drazil100** [comment] 2020-08-14 22:43
Hmm.. Whatever I attempted to do to upgrade it is now leading it to crash I think. Gonna try reverting to an earlier timeshift snapshot. 

While it was probably user error here is the error log.
[error.log](https://github.com/aristocratos/bpytop/files/5077687/error.log)

**Comment by drazil100** [comment] 2020-08-14 23:08
Hold on this is completely unrelated. This is related to using a single color gradient. Putting the same color for all 3 variables fixes the issue.

**Comment by aristocratos** [comment] 2020-08-15 13:16
@drazil100 
Noticed I was only adding 0-99 and not 0-100 colors for single color graphs, will be fixed in next update.

**Comment by aristocratos** [comment] 2020-08-15 16:13
Fixed in v1.0.15

**Closed by aristocratos** 2020-08-15 16:13 UTC
Labels: bug
