### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by iamhrishikeshpadhye** [aristocratos/bpytop#33] opened 2020-08-07 07:32 UTC
**Adding Docker Support**
Most of the platform issues can be resolved by providing Docker support for the application.

**Dockerize the application**
Create a Dockerfile which will be a one step and easy way to execute the application. Also provide the necessary documentation for the same.

**Comment by aristocratos** [comment] 2020-08-07 12:36
Which platform issues are you referring to?

Any problems caused by psutils data collection (which is the most likely to break because of platform) wouldn't be fixed by running in docker, since psutil would need to interact with the host system to get any system information. Otherwise it would be pretty pointless running a system monitor only monitoring the container it's running in...

**Comment by iamhrishikeshpadhye** [comment] 2020-08-07 14:04
I was referring to psutils itself.<br>
It appears that your premise that running psutils in docker would not return the host system information but instead would return system information of the container it's running in, is fallacious.<br>
Subsequently, the conclusion that running in docker wouldn't fix the problems is also incorrect.

**Comment by aristocratos** [comment] 2020-08-07 14:23
> It appears that your premise that running psutils in docker would not return the host system information but instead would return system information of the container it's running in, is fallacious.

Well I didn't claim that psutil wouldn't be using the host system for collection, if not manually setting psutil.PROCFS_PATH it would continue using host system.

So the questing still stands: Which platform issues are you referring to?

Since any issues from reading host system info wouldn't be fixed from running from docker.

> Subsequently, the conclusion that running in docker wouldn't fix the problems is also incorrect.

So could you expand on that? You're claiming something without providing any examples or proof.

**Closed** 2020-08-11 18:55 UTC
Labels: enhancement
