### ISSUE TITLE
[BUG] Crash: bus error on MBP Air M1

### ISSUE THREAD

**Issue by jakobbg** [aristocratos/bpytop#242] opened 2021-01-14 21:07 UTC
**Describe the bug**

Crash on MBP Air M1

**To Reproduce**

* Run on MBP Air M1
* Wait
* Crash

**Expected behavior**

* Running indefinitely

**Info (please complete the following information):**

Running under Rosetta Homebrew, 

bpytop version: 1.0.59 (cc9c7dcc297e9e2fe1f8da54087e9dd46e150754)
psutil version: 5.8.0
Python version: Python 3.8.2
MacOS: Darwin a1r.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 x86_64
Terminal: iTerm2

**Additional context**

contents of `~/.config/bpytop/error.log`

14/01/21 (19:19:28) | INFO: New instance of bpytop version 1.0.59 started with pid 42329
14/01/21 (19:19:28) | INFO: Loglevel set to DEBUG
14/01/21 (19:19:28) | DEBUG: Using psutil version 5.8.0
14/01/21 (19:19:28) | DEBUG: CMD: OneDrive - BKK AS/@Jakob/git/bpytop/bpytop.py --debug
14/01/21 (19:19:30) | DEBUG: Collect and draw completed in 0.259425 seconds
14/01/21 (19:19:31) | DEBUG: Init completed in 2.872058 seconds

**Comment by jakobbg** [comment] 2021-01-14 21:08
Please advise if there is any more context I can supply, I know this is sparse. Takes 1-5 hours before it crashes.

**Comment by aristocratos** [comment] 2021-01-15 14:28
@jakobbg 
> Please advise if there is any more context I can supply, I know this is sparse.

Yeah, the actual error message you get when it crashes :)

I have never run to any issues running on my Mac mini M1, I do however usually not let it run for very long periods and I'm running on native (arm64) python 3.9, will leave it running overnight and see if anything happens.

**Comment by jakobbg** [comment] 2021-01-15 21:23
No error message, unfortunately. Just what I sent: "bus error".

**Comment by aristocratos** [comment] 2021-01-15 21:56
@jakobbg 
In that case I'm pretty sure it's not a bug in `bpytop` but rather one or more levels higher up, like the python interpreter itself or rather rosetta 2 that's crashing. Since python would spew out an error if the script got an exception.

I would suggest you try installing through native python3 using pip and see if the same error happens.

**Comment by aristocratos** [comment] 2021-01-16 08:26
@jakobbg 
Can't reproduce this on my Mac Mini M1 making me even more certain this is not an issue with Apple Silicon hardware.

**Comment by jakobbg** [comment] 2021-01-21 14:18
Seemingly a Rosetta 2-related problem, since I've now run it under native iTerm2 for days without any problem. If problem is Rosetta 2 or iTerm2, I do not know :-).

**Comment by aristocratos** [comment] 2021-01-21 17:29
It's likely Rosetta 2 that's the issue.

Closing this for now since to the best of my knowledge there is nothing I can do about it.

**Closed by aristocratos** 2021-01-21 17:29 UTC
Labels: bug

**Comment by jakobbg** [comment] 2021-01-22 11:57
Issue located. My fault (of course). *doh*

**Explanation**
* Had installed Homebrew using Rosetta 2 and used the "old" x86 system.
* Uninstalled "old" x86 Homebrew
* Installed new ARM Homebrew system
* Tried launching tmux, which still was running a server in memory from old, deleted, system
* Error appeared (since whole x86 Homebrew was gong)

All fixed with a quick ```tmux kill-server ; tmux -vv new```. Sorry for any braincycles spent on this.
