### ISSUE TITLE
Upgrade of bpytop on OpenSUSE 15.2

### ISSUE THREAD

**Issue by evan-shaw** [aristocratos/bpytop#292] opened 2021-04-14 19:24 UTC
**Is your feature request related to a problem? Please describe.**
I've been running bpytop on OpenSUSE 15.2 for some time now but it is stuck on version 1.0.54

**Describe the solution you'd like**
I noticed that release 1.0.63 is available for other linux distributions, can this be released for OpenSUSE?

**Describe alternatives you've considered**
None

**Additional context**
pip3 install bpytop --upgrade
Requirement already satisfied: bpytop in /usr/lib/python3.6/site-packages (1.0.54)
Requirement already satisfied: psutil<6.0.0,>=5.7.0 in /usr/lib64/python3.6/site-packages (from bpytop) (5.8.0)

**Comment by aristocratos** [comment] 2021-04-15 14:56
@evan-shaw 
Duplicate of #273

**Closed** 2021-04-25 11:27 UTC
Labels: enhancement
