### ISSUE TITLE
[BUG] Crashes running in Termux

### ISSUE THREAD

**Issue by NTBBloodbath** [aristocratos/bpytop#149] opened 2020-10-18 03:04 UTC
**Describe the bug**
```
Module 'os' has no attribute 'getloadavg'
```
when bpytop is finishing loading

**To Reproduce**

Just run bpytop

**Expected behavior**

bpytop starts without problems

**Info:**
 - bpytop version: `1.0.42`
 - psutil version: `5.7.2`
 - Terminal used: Termux (Android)
 - Font used: FiraCode
 - Python version, `3.9.0`:

**Additional context**

contents of `~/.config/bpytop/error.log`:
```
17/10/20 (22:51:41) | ERROR: Data collection thread failed with exception: module 'os' has no attribute 'getloadavg'

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/bpytop.py", line 2597, in _runner
    collector._collect()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/bpytop.py", line 2704, in _collect
    cls.load_avg = [round(lavg, 2) for lavg in os.getloadavg()]
AttributeError: module 'os' has no attribute 'getloadavg'
17/10/20 (22:51:41) | WARNING: Exiting with errorcode (1). Runtime 0:00:03

17/10/20 (22:51:54) | ERROR: <urlopen error _ssl.c:1105: The handshake operation timed out>
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/data/data/com.termux/files/usr/lib/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1105: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/bpytop.py", line 4273, in _checker
    with urllib.request.urlopen("https://github.com/aristocratos/bpytop/raw/master/bpytop.py", timeout=5) as source: # type: ignore
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:1105: The handshake operation timed out>
```

**Comment by aristocratos** [comment] 2020-10-18 07:31
Duplicate of https://github.com/aristocratos/bpytop/issues/144

**Closed by aristocratos** 2020-10-18 07:31 UTC
Labels: bug

**Comment by NTBBloodbath** [comment] 2020-10-23 17:20
> Duplicate of https://github.com/aristocratos/bpytop/issues/144

That both happen on the same platform doesn't make it a duplicate, as far as I know? 🤨

**Comment by aristocratos** [comment] 2020-10-23 17:34
@NTBBloodbath 
Android is not a supported platform. So any bugs relating to it would fall under the request of making bpytop supported on Android.

@TheComputerGuy96 posted a screenshot in #144 , which could be it running on Android. But there is no more information than the screenshot so it's not very illuminating.

**Comment by NTBBloodbath** [comment] 2020-10-23 17:36
I understand, thanks for the clarification!
