### ISSUE TITLE
[BUG] IndexError after resuming from Standby

### ISSUE THREAD

**Issue by h4p** [aristocratos/bpytop#103] opened 2020-09-02 08:08 UTC
**Describe the bug**

Program crashes when returning from standby on macOS.

**To Reproduce**

Start the program with bpytop in terminal. Close the lid. After opening the lid and logging in the program has stopped.

**Expected behavior**

The program resumes after returning from standby

**Info:**
> python --version                                                                                                
Python 3.8.1

> bpytop -v                                                                                               
bpytop version: 1.0.21
psutil version: 5.7.2

Running on: macOS 10.15.6 (Catalina) in iTerm2 Build 3.1.6

**Additional context**

01/09/20 (18:55:59) | ERROR: Data collection thread failed with exception: list index out of range
Traceback (most recent call last):
  File "/Users/twe/venvs/bpytop/lib/python3.8/site-packages/bpytop.py", line 2417, in _runner
    collector._draw()
  File "/Users/twe/venvs/bpytop/lib/python3.8/site-packages/bpytop.py", line 2619, in _draw
    CpuBox._draw_fg()
  File "/Users/twe/venvs/bpytop/lib/python3.8/site-packages/bpytop.py", line 1604, in _draw_fg
    out += (f'{THEME.inactive_fg} ⡀⡀⡀⡀⡀{Mv.l(5)}{THEME.gradient["temp"][100 if cpu.cpu_temp[0][-1] >= cpu.cpu_temp_crit else (cpu.cpu_temp[0][-1] * 100 // cpu.cpu_temp_crit)]}{Graphs.temps[0](None if cls.resized else cpu.cpu_temp[0][-1])}'
IndexError: list index out of range
01/09/20 (18:55:59) | WARNING: Exiting with errorcode (1). Runtime 0:05:16

**Comment by aristocratos** [comment] 2020-09-05 12:59
@h4p 
Can't reproduce this in a virtual machine and don't have real mac to test on.
It could be `osx-cpu-temp` acting weird after resume from sleep.

Can you test if you get the same error if you set `check_temp` to False and then sleep and resume.

**Comment by h4p** [comment] 2020-09-07 13:38
osx-cpu-temp does seem to be the problem! After setting check_temp to false the program runs stable.

**Comment by aristocratos** [comment] 2020-09-07 14:39
@h4p 
Good to know. I'm gonna look in to finding a workaround so you don't have to sacrifice the temp monitoring.

**Comment by aristocratos** [comment] 2020-09-07 18:49
@h4p 
Should be fixed in v1.0.26

Reopen this otherwise.

**Closed by aristocratos** 2020-09-07 18:49 UTC
Labels: bug
