### ISSUE TITLE
[BUG] Network graph/data not always consistent with displayed network interface name

### ISSUE THREAD

**Issue by applike-ss** [aristocratos/bpytop#265] opened 2021-02-18 07:08 UTC
**Describe the bug**

When starting bpytop the network graph and all of its data is consistent.

However over the day i suddenly see that the download speed/top/total have become upload instead.

I assume that this is actually happening because the "position" of the interface is changing over time.

That could be caused by me using docker a lot and also virtual machines (where i am not sure if those do also dynamically create interfaces).

**To Reproduce**

* start bpytop in a shell and leave it open the whole day.
* use docker a whole day with starting/stopping/removing/starting again containers

**Expected behavior**

The network interfaces name should be consistent with the displayed data.

**Screenshots**

I just had the issue, but did "fix" it by changing the network interface before taking screenshots.

**Info (please complete the following information):**
 - bpytop version: 1.0.62
- psutil version: 5.7.2
- linux version:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
 - Terminal used: Tilix
 - Font used: Monospace regular 12
 - Python version: Python 3.8.5

**Additional context**

no errors observed, but didn't run with --debug yet

**Comment by aristocratos** [comment] 2021-02-18 16:58
@applike-ss 
Hi, can you provide screenshots of this happening?

It does sound like a rendering issue with your terminal since the positioning of all elements in BpyTOP is done by fixed x, y coordinates. Unless you resize the terminal or scroll the terminal (scrolling should be prevented by the used terminal mode) those coordinates never change.

> That could be caused by me using docker a lot and also virtual machines

Not really sure why running containers or virtual machines would have any effect on an unrelated program running in a terminal. Can you expand on what you mean?

**Comment by applike-ss** [comment] 2021-02-22 06:21
> can you provide screenshots of this happening?

i will try to provide a video as soon as i can see it happening again

> Not really sure why running containers or virtual machines would have any effect on an unrelated program running in a terminal. Can you expand on what you mean?

Docker does add and remove virtual network interfaces very dynamically. I assumed that bpytop would possibly rely on a certain position in a list of information to gather ups and downs.

**Comment by applike-ss** [comment] 2021-02-24 07:19
Eventually i got this captured. Please see the video attached.

https://user-images.githubusercontent.com/31846129/108962359-ed0ae780-7678-11eb-908b-af84beef3d25.mp4

**Comment by applike-ss** [comment] 2021-03-08 10:18
Any thoughts on this?

**Comment by aristocratos** [comment] 2021-03-13 11:50
@applike-ss 
These values are collected by `psutil` which in turn reads from `/proc/net/dev`.
There really isn't anyway I can think of that would make it possible for bpytop to mix the two values.

To properly diagnose what's happening you would need to (while this issue is present)
1. Look at the output from `/proc/net/dev`
2. Look at the output from psutil, could be done with `python3 -c "import psutil, pprint; pprint.pprint(psutil.net_io_counters(pernic=True))"`

And see if they differ. If `/proc/net/dev` looks ok but psutil doesn't, you will have to create a bug report at https://github.com/giampaolo/psutil
If `/proc/net/dev` also looks weird, then this would be a problem with the networking in your kernel.

There is also a slim possibility this could be caused by permission errors, but should be easy to test if you run a second instance of bpytop started with sudo.

**Comment by aristocratos** [comment] 2021-03-13 11:55
@applike-ss 
> Docker does add and remove virtual network interfaces very dynamically. I assumed that bpytop would possibly rely on a certain position in a list of information to gather ups and downs.

This shouldn't have any effect since all the interfaces are saved in a dictionary and addressed by name of the interface.

**Comment by applike-ss** [comment] 2021-03-18 06:39
Thank you for your reply, i will keep an eye on it. It did just happen before i read your answer and i did already click the issue away. So i will keep you posted about my findings.

**Comment by applike-ss** [comment] 2021-03-19 07:23
it did just happen again, however when i resized the window (actually did it multiple times and noticed after the last resize), then the interfaces name is suddenly switched to lo - which actually makes sense now to me. So i assume that i accidentally hit the b/n key while the terminal was in focus. Is there a way to disable certain keymappings in bpytop? Btw. thanks for this great piece of software :-D

**Comment by applike-ss** [comment] 2021-03-29 05:51
There is actually something that speaks against me accidentally hitting the b/n key for switching interfaces: The displayed interface name does stay the same all the time (`enp4s0`), even though the displayed data is for `lo`. However since you mentioned a rendering issue in my terminal, i will try a different terminal emulator now.

**Comment by applike-ss** [comment] 2021-03-30 10:18
First i used Tilix, now i tried Terminator which showed the same issue. Will now try UXTerm.

**Comment by applike-ss** [comment] 2021-04-27 06:55
It's still happening, also in UXTerm. I don't think this is terminal related.
I do now use bpytop 1.0.64 with psutil 5.7.2.
It does show me that it would display enp4s0, but it must be the loopback device.

**Comment by UmarJ** [comment] 2021-05-17 21:02
> Eventually i got this captured. Please see the video attached.
> 
>  bpytop_capture.mp4

I'm pretty sure I've figured out what's happening here.

1. You are viewing the interface `enp4s0` at some point before this capture.
2. The interface is **removed** by Docker afterwards (bpytop can handle an interface that goes down while you are viewing it, but not one that is removed).
3. bpytop automatically switches the current interface to `lo` since it has the highest traffic. This switches the data/graph inside of `NetBox` but _the box itself is not redrawn_. The box is only redrawn when you switch interfaces _manually_.
4. You switch interfaces. This time everything is redrawn properly.

I can reproduce this by renaming interfaces with `ip link`. Will open a PR in a bit.

**Comment by aristocratos** [comment] 2021-05-17 22:02
@applike-ss
Well, seems this was my mistake after all :P

@UmarJ 
Great solve! Will take a look at the PR.

**Comment by applike-ss** [comment] 2021-05-27 13:52
Insane! Why would docker remove that interface only to add it back later. :see_no_evil: 

However i noticed that my connections are often shortly aborted when running my integration tests, but i didn't take the time to look into that more closely.

Nice find @UmarJ !

Great to know this will be resolved soon :-D

**Closed** 2021-05-30 19:17 UTC
Labels: bug

**Comment by aristocratos** [comment] 2021-05-30 19:28
@applike-ss 
Fixed in v1.0.66

**Comment by applike-ss** [comment] 2021-06-01 06:43
i can confirm that it indeed switched the network interface and showed the correct name after doing so. Thanks!
