### ISSUE TITLE
Not possible to exit bpytop in a small terminal

### ISSUE THREAD

**Issue by jmrf** [aristocratos/bpytop#290] opened 2021-04-12 16:25 UTC
**Describe the bug**

On a small terminal (smaller than the minimum size to render) bpytop continues to display the message: 
`Width and Height needs to be at least  80 x 24!` even after pressing `q` leaving the terminal iresponsive until resized back to a larger size and bpytop exists.

**To Reproduce**

 - Start bpytop in a big enough terminal (size > 80 x 24)
 - Resize the terminal to a size smaller than the minimum render size 
   (the message `Width and Height needs to be at least 80 x 24!` becomes visible)
 - Press `q` to exit (the terminal still shows the above message) and is not possible to close bpytop
 - Resize the terminal back to its original size. bpytop exists

**Expected behavior**

bpytop should still exit even if the terminal is to small (respond to `q` key) without having to resize the terminal to a larger size

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - bpytop version: `1.0.57`
 - psutil version: `5.8.0`
 - (Linux) Linux distribution and version: `Ubuntu 18.04`
 - (OSX/FreeBSD) Os release version:
 - Terminal used: `Gnome Terminal 3.28.2`
 - Font used:
 - Python version, `python3 --version` (version 3.6 or above is required): `Python 3.7.4`

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment] 2021-04-25 11:47
@jmrf
You can exit out with `CTRL + c` SIGINT.

**Comment by jmrf** [comment] 2021-04-25 12:00
Hey @aristocratos thanks for getting back to me with this.

Actually, doing the same as described above but hitting `ctrl+c` instead of `q` has a similar behavior (while the terminal is too small `ctrl+c` won't make the warning screen go away) and once the terminal is resized to a larger size the terminal becomes stuck on the warning and not responding to any command (not even `ctrl+c` again or any other signal).

**Comment by aristocratos** [comment] 2021-04-25 12:08
@jmrf 
> bpytop version: 1.0.57

Can't reproduce.
Try with latest version: 1.0.63

**Comment by jmrf** [comment] 2021-04-25 12:25
Interesting... I just tried with version `1.0.63` and I am seeing the same behavior. Both for `q` and `ctrl+c`.

Will try to try on another system and report back here any findings.

**Comment by aristocratos** [comment] 2021-04-25 12:30
@jmrf 
Will take a look at it when I've got time and make sure the `q` key does what it's intended to do too.

**Comment by aristocratos** [comment] 2021-05-02 09:00
@jmrf 
Should be fixed in v1.0.65

**Closed by aristocratos** 2021-05-02 09:00 UTC
Labels: bug
