### ISSUE TITLE
[REQUEST] Bar graph CPU activity display mode

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#118] opened 2020-09-12 23:04 UTC
While I really like the symmetrical CPU graph display mode, I keep wondering if sometimes it would be nice to switch to a bottom-up bar graph type of activity display. I think a lot of users may like having this as an option. 

Take this as a very low priority.

**Comment by aristocratos** [comment] 2020-09-13 00:33
@RedBearAK 
Should be easy enough to implement, will take a look at it when I've got time.

I've been planning on creating another alternate layout for the cpu box were all the cores are displayed as graphs in boxes with rows and columns adapted to the size of the whole cpu box. Haven't had time to work on yet.

**Comment by RedBearAK** [comment] 2020-09-13 01:52
@aristocratos 

>I've been planning on creating another alternate layout for the cpu box were all the cores are displayed as graphs in boxes with rows and columns adapted to the size of the whole cpu box. Haven't had time to work on yet.

That's funny, that is pretty much the other mode I was going to suggest working on. But I didn't know quite how to describe it, and it seemed like it might be quite a bit more complicated than simply switching the graph from symmetrical to asymmetrical. So I didn't want to get into it. But I look forward to seeing it if you ever find the time. 

I think the asymmetrical graph will already prove quite popular. For some minds it will actually be a more logical presentation of CPU activity. The symmetrical network graph makes sense because there is "up" and "down" activity to represent, and it's a logical way to visualize it. But you have to admit that the CPU graph being symmetrical is just an aesthetic choice. Some will prefer it in a more standard orientation, and others like me will love to switch things up depending on how we feel that day. 

Don't work too hard. 

And don't even think about making sure the multi-core graph mode could also be switched between different render modes like symmetrical or asymmetrical. Don't imagine that with 64 cores / 128 threads. 

[insert Indiana_Jones_melting_face.gif here]

**Comment by loki7990** [comment] 2020-09-23 23:46
I can understand if this isn't desirable, but would it be possible to have htop-style bars as an option to the display the cpu? I'll admit, that was one thing I did like about htop. Your comment sort of sounds like it (https://github.com/aristocratos/bpytop/issues/118#issuecomment-691580738) but I wasn't sure so I figured here would be a good spot to request it.

**Comment by SirNapkin1334** [comment] 2020-10-31 20:37
I just wanted to pitch in with the mockups I made for my issue, which is a duplicate of this. Just some ideas.
![image](https://user-images.githubusercontent.com/31591796/97789491-283f5300-1b7e-11eb-92b7-4c345ca9489c.png) 

![image](https://user-images.githubusercontent.com/31591796/97789493-2aa1ad00-1b7e-11eb-9b5e-a375795bcd97.png)

**Comment by aristocratos** [comment] 2021-01-23 01:17
@RedBearAK 
Added in v1.0.60

**Closed by aristocratos** 2021-01-23 01:17 UTC
Labels: enhancement

**Comment by RedBearAK** [comment] 2021-01-26 02:36
@aristocratos 

Man, you even moved the uptime into the top corner so that it won't interfere with the CPU graph in that mode. Fantastic. Thanks for that. It looks great. Exceeded expectations.
