### ISSUE TITLE
[REQUEST] allow placing the 0-point of the CPU graph at the bottom, like the memory graphs

### ISSUE THREAD

**Issue by SirNapkin1334** [aristocratos/bpytop#178] opened 2020-10-31 20:32 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the CPU graph's 0-point is centered around the middle of the CPU window, and it's a mirrored graph. It would be nice to allow the graph to start at the bottom, and utilize the entirety of the window for more precision.

**Describe the solution you'd like**
[Example I made in GIMP.](https://user-images.githubusercontent.com/31591796/97789170-7b63d680-1b7b-11eb-8c3d-09bad852b14e.png) Now obviously, this is a pretty rough mockup, and deciding where to put the CPU info block would be difficult. Maybe it could be in the upper left corner along with the uptime data, cutting off a bit of the past data. But, I think it gets the gist across. This would also allow for more precision, since now you have effectively double the vertical area for the graph, meaning that each point is twice as precise. Additionally, if you are moving the CPU info to, say, to the top, then you also have more lateral area where the CPU info used to be.

**Describe alternatives you've considered**
This is a pretty binary PR, so you could just...not do it, but besides that I don't really see anything else.

**Additional context**
[Another mockup](https://user-images.githubusercontent.com/31591796/97789377-32ad1d00-1b7d-11eb-8f19-2b81257eecfd.png)

**Comment by aristocratos** [comment] 2020-10-31 20:35
@SirNapkin1334 
Duplicate of #118 
Haven't gotten to it yet, will do when I have time.

**Comment by SirNapkin1334** [comment] 2020-10-31 20:36
Oh, alright, sorry about that. I was skimming the titles of open issues and the title of that issue didn't clue me in.

**Closed by aristocratos** 2020-10-31 20:35 UTC
Labels: duplicate, enhancement

**Comment by aristocratos** [comment] 2020-10-31 20:37
No worries, might not be the most obvious title.
