### ISSUE TITLE
[BUG] starting up in minimode gives choped cpu name

### ISSUE THREAD

**Issue by bgkillas** [aristocratos/bpytop#24] opened 2020-08-05 07:20 UTC
![image](https://user-images.githubusercontent.com/55570525/89383448-7ef5d780-d6ca-11ea-9161-8bbb34506efb.png)
when its ment to look like
![image](https://user-images.githubusercontent.com/55570525/89383483-903ee400-d6ca-11ea-8c4f-b6f5d8b0e378.png)
going in and out of mini mode fixes it

**Comment by aristocratos** [comment] 2020-08-05 13:55
I can't reproduce the issue. It would be helpful if you provided the asked for info from the bug report template.

**Comment by bgkillas** [comment] 2020-08-05 16:56
bpytop version: 1.0.3
psutil version: 5.7.2
 - (Linux) Linux distribution and version: arch linux
 - Terminal used: alacritty
 - Font used: noto sans mono 14
 - Python version, Python 3.8.5

also with default config
![image](https://user-images.githubusercontent.com/55570525/89439030-98714080-d717-11ea-9698-464e0d59adce.png)

**Comment by aristocratos** [comment] 2020-08-05 18:06
This might be related to #25 since you got cores with numbers over 2 digits.

I'm currently working on it, so hopefully that fixes this issue too.

**Comment by aristocratos** [comment] 2020-08-05 20:04
Should hopefully be fixed in v1.0.4

**Closed** 2020-08-05 20:17 UTC
Labels: bug
